version: '2'

services:

  cdx:
    image: ukwa/tinycdxserver:ukwa-production
    #ports:
    #  - "9090:8080"
  
  hadoop:
    build:
      context: ./hadoop/
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    command: "/etc/bootstrap.sh -d"
    ports:
      - "50070:50070"
      - "50075:50075"
    hostname: hadoop

  owb:
    image: ukwa/waybacks
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=qa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://hadoop:50070/webhdfs/v1/"
      - "CDX_INDEX_SERVER=http://cdx:8080/tc"
      - "WAYBACK_URL_PREFIX=http://localhost:8080"
      - "WAYBACK_URL_HOST=localhost" 

  populate:
    image: sequenceiq/alpine-curl
    command: /test-data/populate.sh
    volumes:
      - ./test-data/:/test-data

  redis:
    image: redis:3.2.4

  pywb:
    build:
      context: ..
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    volumes:
      - ../integration-test/test-data/:/webarchive/integration-test/test-data:ro
      - ../integration-test/test-data/video-test/:/ukwa_pywb/collections/video-test:ro

    environment:
      - "UKWA_INDEX=xmlquery+http://cdx:8080/tc"
      - "UKWA_ARCHIVE=webhdfs://hadoop:50070/"
      - "WEBHDFS_USER=hadoop"
      - "REDIS_URL=redis://redis:6379/0"
      - "TEST_SESSION_LOCK_INTERVAL=30"
      - "DEBUG=True"

    ports:
      - "8082:8080"

    depends_on:
      - cdx
      - hadoop
      - redis

  nginx:
    image: nginx:1.13-alpine

    volumes:
      - ./nginx/pywb.conf:/etc/nginx/conf.d/pywb.conf:ro
      - ../static:/ukwa-pywb-static

    ports:
      - "8100:8100"

    depends_on:
      - pywb


# -----------------------------------------------------------
# Automated test engine
# -----------------------------------------------------------

  test:
    build:
      context: ./robot/
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    #command: -v BROWSER:ff --outputdir /out /tests
    command: --outputdir /out /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/locktest:/out:rw
      - ./robot/make_profile.py:/tmp/make_profile.py
      - ../proxy-certs:/tmp/proxy-certs
    depends_on:
      - pywb
      - firefox
      - chrome
      - hub

  firefox:
    image: selenium/node-firefox:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.9.1-actinium
    ports:
      - "4444:4444"

